// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfpubgzdrrlpdygkgkno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcHViZ3pkcnJscGR5Z2tna25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTkyNjgsImV4cCI6MjA2NTI5NTI2OH0.7goh9BlBGZeKwdRLTwm-xPoMK_O7gOsWJtt1TU6SC_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);